apiVersion: v1
kind: Pod
metadata:
  name: er1
spec:
  containers:
    - image: quay.io/connordoyle/cpuset-visualizer
      name: er1
      resources:
        requests:
          example.com/foo: 1
          cpu: "100m"
          memory: "128M"
