apiVersion: v1
kind: Pod
metadata:
  name: er2
spec:
  containers:
    - image: quay.io/connordoyle/cpuset-visualizer
      name: er2
      resources:
        requests:
          example.com/bar: 1
          cpu: "100m"
          memory: "128M"
